[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
identity_reputation = "4DNAXZBUwD8ejo6UEDzbq89faMjARWwV6DuWJMKHnyDm"

[programs.localnet]
identity_reputation = "AW3tnz9dMLYQz5deDNKV9bCuX77sNundHrcuD6oVS5Zi"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
