/**
 * IDL (Interface Definition Language) for the identity-reputation Anchor program.
 *
 * Auto-generated by `anchor build` — Anchor 0.30.1 new-format IDL.
 * Program deployed on Solana Devnet.
 */

export const PROGRAM_ID = "4DNAXZBUwD8ejo6UEDzbq89faMjARWwV6DuWJMKHnyDm";

export const IDL = {
  address: "4DNAXZBUwD8ejo6UEDzbq89faMjARWwV6DuWJMKHnyDm",
  metadata: {
    name: "identityReputation",
    version: "0.1.0",
    spec: "0.1.0",
    description:
      "Decentralized identity and reputation system built with Anchor",
  },
  instructions: [
    {
      name: "createProfile",
      docs: [
        "Create a new user profile tied to the caller's wallet.",
        "Each wallet can only ever hold one profile (enforced by PDA seeds).",
      ],
      discriminator: [225, 205, 234, 143, 17, 186, 50, 220],
      accounts: [
        {
          name: "profile",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [112, 114, 111, 102, 105, 108, 101] },
              { kind: "account", path: "wallet" },
            ],
          },
        },
        { name: "wallet", writable: true, signer: true },
        {
          name: "systemProgram",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [{ name: "username", type: "string" }],
    },
    {
      name: "submitWork",
      docs: [
        "Submit a new work record linked to the caller's profile.",
        '`job_id` uniquely identifies the job; `proof_link` points to evidence (e.g. IPFS, Arweave).',
      ],
      discriminator: [158, 80, 101, 51, 114, 130, 101, 253],
      accounts: [
        {
          name: "profile",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [112, 114, 111, 102, 105, 108, 101] },
              { kind: "account", path: "wallet" },
            ],
          },
        },
        {
          name: "workRecord",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [119, 111, 114, 107] },
              { kind: "account", path: "profile" },
              { kind: "arg", path: "jobId" },
            ],
          },
        },
        {
          name: "wallet",
          writable: true,
          signer: true,
          relations: ["profile"],
        },
        {
          name: "systemProgram",
          address: "11111111111111111111111111111111",
        },
      ],
      args: [
        { name: "jobId", type: "string" },
        { name: "proofLink", type: "string" },
      ],
    },
    {
      name: "verifyWork",
      docs: [
        "Mark a work record as verified and reward the owner with +10 reputation.",
        "Only the designated verifier (a trusted off-chain authority) may call this.",
      ],
      discriminator: [180, 2, 137, 185, 109, 244, 60, 89],
      accounts: [
        {
          name: "profile",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [112, 114, 111, 102, 105, 108, 101] },
              {
                kind: "account",
                path: "profile.wallet",
                account: "userProfile",
              },
            ],
          },
          relations: ["workRecord"],
        },
        {
          name: "workRecord",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [119, 111, 114, 107] },
              { kind: "account", path: "profile" },
              {
                kind: "account",
                path: "work_record.job_id",
                account: "workRecord",
              },
            ],
          },
        },
        { name: "verifier", signer: true },
      ],
      args: [],
    },
    {
      name: "rejectWork",
      docs: [
        "Reject a work record and penalise the owner by -5 reputation.",
        "Reputation is floored at 0 — it cannot go negative.",
        "Only the designated verifier may call this.",
      ],
      discriminator: [129, 238, 59, 133, 63, 148, 130, 54],
      accounts: [
        {
          name: "profile",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [112, 114, 111, 102, 105, 108, 101] },
              {
                kind: "account",
                path: "profile.wallet",
                account: "userProfile",
              },
            ],
          },
          relations: ["workRecord"],
        },
        {
          name: "workRecord",
          writable: true,
          pda: {
            seeds: [
              { kind: "const", value: [119, 111, 114, 107] },
              { kind: "account", path: "profile" },
              {
                kind: "account",
                path: "work_record.job_id",
                account: "workRecord",
              },
            ],
          },
        },
        { name: "verifier", signer: true },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: "userProfile",
      discriminator: [32, 37, 119, 205, 179, 180, 13, 194],
    },
    {
      name: "workRecord",
      discriminator: [92, 226, 123, 227, 214, 85, 246, 85],
    },
  ],
  events: [
    {
      name: "profileCreated",
      discriminator: [134, 233, 199, 153, 77, 206, 128, 94],
    },
    {
      name: "workReviewed",
      discriminator: [167, 126, 185, 247, 67, 32, 194, 197],
    },
    {
      name: "workSubmitted",
      discriminator: [136, 185, 210, 174, 216, 140, 64, 125],
    },
  ],
  errors: [
    {
      code: 6000,
      name: "invalidUsername",
      msg: "Username must be between 1 and 50 characters.",
    },
    {
      code: 6001,
      name: "invalidJobId",
      msg: "Job ID must be between 1 and 50 characters.",
    },
    {
      code: 6002,
      name: "invalidProofLink",
      msg: "Proof link must be between 1 and 200 characters.",
    },
    {
      code: 6003,
      name: "alreadyVerified",
      msg: "This work record has already been verified and cannot be reviewed again.",
    },
  ],
  types: [
    {
      name: "profileCreated",
      type: {
        kind: "struct" as const,
        fields: [
          { name: "wallet", type: "pubkey" },
          { name: "username", type: "string" },
        ],
      },
    },
    {
      name: "userProfile",
      type: {
        kind: "struct" as const,
        fields: [
          { name: "wallet", type: "pubkey" },
          { name: "username", type: "string" },
          { name: "reputationScore", type: "u32" },
          { name: "workCount", type: "u32" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "workRecord",
      type: {
        kind: "struct" as const,
        fields: [
          { name: "profile", type: "pubkey" },
          { name: "jobId", type: "string" },
          { name: "proofLink", type: "string" },
          { name: "verified", type: "bool" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "workReviewed",
      type: {
        kind: "struct" as const,
        fields: [
          { name: "profile", type: "pubkey" },
          { name: "jobId", type: "string" },
          { name: "accepted", type: "bool" },
          { name: "newReputation", type: "u32" },
        ],
      },
    },
    {
      name: "workSubmitted",
      type: {
        kind: "struct" as const,
        fields: [
          { name: "profile", type: "pubkey" },
          { name: "jobId", type: "string" },
        ],
      },
    },
  ],
} as const;

export type IdentityReputationIDL = typeof IDL;
